In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
housing = pd.read_csv('..\Python-Practice-code\housing.csv')

In [3]:
housing[:5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
# same can be performed using head function which can take argument also. without giving argument it prints first 5
# records by default

In [5]:
housing.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   
5    -122.25     37.85                52.0        919.0           213.0   
6    -122.25     37.84                52.0       2535.0           489.0   
7    -122.25     37.84                52.0       3104.0           687.0   
8    -122.26     37.84                42.0       2555.0           665.0   
9    -122.25     37.84                52.0       3549.0           707.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  
5       413.0       193.0         4.0368            269700.0        NEAR BAY  
6      1094.0       514.0         3.6591            299200.0        NEAR BAY  
7      1157.0       647.0         3.1200            241400.0        NEAR BAY  
8      1206.0       595.0         2.0804            226700.0        NEAR BAY  
9      1551.0       714.0         3.6912            261100.0        NEAR BAY

In [6]:
housing.to_json('..\Python-Practice-code\housing.json')

In [7]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


# Showing statistical information 

In [8]:
housing.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [9]:
housing.hist(bins = 60, figsize=(20,15))

d:\python-practice-code\venv\lib\site-packages\pandas\plotting\_matplotlib\tools.py:400: MatplotlibDeprecationWarning: 
The is_first_col function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use ax.get_subplotspec().is_first_col() instead.
  if ax.is_first_col():


array([[<AxesSubplot:title={'center':'longitude'}>,
        <AxesSubplot:title={'center':'latitude'}>,
        <AxesSubplot:title={'center':'housing_median_age'}>],
       [<AxesSubplot:title={'center':'total_rooms'}>,
        <AxesSubplot:title={'center':'total_bedrooms'}>,
        <AxesSubplot:title={'center':'population'}>],
       [<AxesSubplot:title={'center':'households'}>,
        <AxesSubplot:title={'center':'median_income'}>,
        <AxesSubplot:title={'center':'median_house_value'}>]],
      dtype=object)

In [10]:
corr = housing.corr()

In [11]:
corr

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.924664           -0.108197     0.044568   
latitude            -0.924664  1.000000            0.011173    -0.036100   
housing_median_age  -0.108197  0.011173            1.000000    -0.361262   
total_rooms          0.044568 -0.036100           -0.361262     1.000000   
total_bedrooms       0.069608 -0.066983           -0.320451     0.930380   
population           0.099773 -0.108785           -0.296244     0.857126   
households           0.055310 -0.071035           -0.302916     0.918484   
median_income       -0.015176 -0.079809           -0.119034     0.198050   
median_house_value  -0.045967 -0.144160            0.105623     0.134153   

                    total_bedrooms  population  households  median_income  \
longitude                 0.069608    0.099773    0.055310      -0.015176   
latitude                 -0.066983   -0.108785   -0.071035      -0.079809   
housing_median_age       -0.320451   -0.296244   -0.302916      -0.119034   
total_rooms               0.930380    0.857126    0.918484       0.198050   
total_bedrooms            1.000000    0.877747    0.979728      -0.007723   
population                0.877747    1.000000    0.907222       0.004834   
households                0.979728    0.907222    1.000000       0.013033   
median_income            -0.007723    0.004834    0.013033       1.000000   
median_house_value        0.049686   -0.024650    0.065843       0.688075   

                    median_house_value  
longitude                    -0.045967  
latitude                     -0.144160  
housing_median_age            0.105623  
total_rooms                   0.134153  
total_bedrooms                0.049686  
population                   -0.024650  
households                    0.065843  
median_income                 0.688075  
median_house_value            1.000000

In [12]:
corr['median_house_value'].sort_values(ascending = False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [13]:
len(housing['median_income'].unique())

12928

In [14]:
housing.median_income.min()

0.4999

In [15]:
housing.median_income.max()

15.0001

In [16]:
housing['income_cat']=np.ceil(housing['median_income'] / 1.5)

In [17]:
housing['income_cat'].unique()

array([ 6.,  5.,  4.,  3.,  2.,  1.,  8.,  7.,  9., 11., 10.])

In [18]:
housing['income_cat'].value_counts()

3.0     7236
2.0     6581
4.0     3639
5.0     1423
1.0      822
6.0      532
7.0      189
8.0      105
9.0       50
11.0      49
10.0      14
Name: income_cat, dtype: int64

In [19]:
housing['income_cat'].value_counts().sort_index(ascending = True)

1.0      822
2.0     6581
3.0     7236
4.0     3639
5.0     1423
6.0      532
7.0      189
8.0      105
9.0       50
10.0      14
11.0      49
Name: income_cat, dtype: int64

In [20]:
# capping - where it's finding the value more than 5 then it's replacing those values with 5
housing['income_cat'].where(housing['income_cat']< 5, 5, inplace = True)

In [21]:
housing['income_cat']

0        5.0
1        5.0
2        5.0
3        4.0
4        3.0
        ... 
20635    2.0
20636    2.0
20637    2.0
20638    2.0
20639    2.0
Name: income_cat, Length: 20640, dtype: float64

In [22]:
housing['income_cat'].value_counts().sort_index(ascending = True)

1.0     822
2.0    6581
3.0    7236
4.0    3639
5.0    2362
Name: income_cat, dtype: int64

In [23]:
from sklearn.model_selection import StratifiedShuffleSplit

In [24]:
strat_split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)

In [25]:
g = strat_split.split(housing, housing['income_cat'])

In [26]:
for train_ix, test_ix in g:
    strat_train_split = housing.iloc[train_ix]
    strat_test_split = housing.iloc[test_ix]

In [27]:
housing['income_cat'].value_counts().sort_index() / len(housing)

1.0    0.039826
2.0    0.318847
3.0    0.350581
4.0    0.176308
5.0    0.114438
Name: income_cat, dtype: float64

In [28]:
strat_train_split['income_cat'].value_counts().sort_index() / len(strat_train_split)

1.0    0.039850
2.0    0.318859
3.0    0.350594
4.0    0.176296
5.0    0.114402
Name: income_cat, dtype: float64

In [29]:
strat_test_split['income_cat'].value_counts().sort_index() / len(strat_test_split)

1.0    0.039729
2.0    0.318798
3.0    0.350533
4.0    0.176357
5.0    0.114583
Name: income_cat, dtype: float64

In [30]:
strat_train_split = strat_train_split.drop('income_cat', axis = 1)
strat_test_split = strat_test_split.drop('income_cat', axis = 1)

In [31]:
X_train = strat_train_split.drop('median_house_value', axis = 1)
y_train = strat_train_split['median_house_value'].copy()
X_test = strat_test_split.drop('median_house_value',axis = 1)
y_test = strat_test_split['median_house_value'].copy()

# Data Preprocessing

## Dividing into Numeric and categorical

In [32]:
X_train_num = X_train.drop('ocean_proximity', axis=1)

In [33]:
X_train_num.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 17606 to 15775
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16354 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.1 MB


In [34]:
X_train_cat=X_train['ocean_proximity']

## Null value Imputation

In [35]:
from sklearn.impute import SimpleImputer

In [36]:
imputer = SimpleImputer(strategy='median')

In [37]:
imputer.fit(X_train_num)

SimpleImputer(strategy='median')

In [38]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [39]:
X_train_num

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income  
17606       710.0       339.0         2.7042  
18632       306.0       113.0         6.4214  
14650       936.0       462.0         2.8621  
3230       1460.0       353.0         1.8839  
3555       4459.0      1463.0         3.0347  
...           ...         ...            ...  
6563        573.0       210.0         4.9312  
12053      1052.0       258.0         2.0682  
13908      2098.0       765.0         3.2723  
11159      1356.0       356.0         4.0625  
15775      1269.0       639.0         3.5750  

[16512 rows x 8 columns]

In [40]:
x_train_num_imputed_arr = imputer.transform(X_train_num)

In [41]:
x_train_num_imputed_arr

array([[-121.89  ,   37.29  ,   38.    , ...,  710.    ,  339.    ,
           2.7042],
       [-121.93  ,   37.05  ,   14.    , ...,  306.    ,  113.    ,
           6.4214],
       [-117.2   ,   32.77  ,   31.    , ...,  936.    ,  462.    ,
           2.8621],
       ...,
       [-116.4   ,   34.09  ,    9.    , ..., 2098.    ,  765.    ,
           3.2723],
       [-118.01  ,   33.82  ,   31.    , ..., 1356.    ,  356.    ,
           4.0625],
       [-122.45  ,   37.77  ,   52.    , ..., 1269.    ,  639.    ,
           3.575 ]])

In [42]:
type(x_train_num_imputed_arr)

numpy.ndarray

In [43]:
x_train_num_df = pd.DataFrame(X_train_num, columns=X_train_num.columns)

In [44]:
x_train_num_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income  
17606       710.0       339.0         2.7042  
18632       306.0       113.0         6.4214  
14650       936.0       462.0         2.8621  
3230       1460.0       353.0         1.8839  
3555       4459.0      1463.0         3.0347  
...           ...         ...            ...  
6563        573.0       210.0         4.9312  
12053      1052.0       258.0         2.0682  
13908      2098.0       765.0         3.2723  
11159      1356.0       356.0         4.0625  
15775      1269.0       639.0         3.5750  

[16512 rows x 8 columns]

In [45]:
x_train_num_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 17606 to 15775
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16354 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.1 MB


In [46]:
## no null values are in X_train_num_df

## Scaling

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler = StandardScaler()

In [49]:
x_train_num_imputed_scaled = scaler.fit_transform(x_train_num_imputed_arr)

In [50]:
x_train_num_imputed_scaled

array([[-1.15604281,  0.77194962,  0.74333089, ..., -0.63621141,
        -0.42069842, -0.61493744],
       [-1.17602483,  0.6596948 , -1.1653172 , ..., -0.99833135,
        -1.02222705,  1.33645936],
       [ 1.18684903, -1.34218285,  0.18664186, ..., -0.43363936,
        -0.0933178 , -0.5320456 ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.60790363,
         0.71315642, -0.3167053 ],
       [ 0.78221312, -0.85106801,  0.18664186, ..., -0.05717804,
        -0.37545069,  0.09812139],
       [-1.43579109,  0.99645926,  1.85670895, ..., -0.13515931,
         0.3777909 , -0.15779865]])

In [51]:
x_train_num_ndarray = scaler.fit_transform(x_train_num_df)

In [52]:
x_train_num_ndarray

array([[-1.15604281,  0.77194962,  0.74333089, ..., -0.63621141,
        -0.42069842, -0.61493744],
       [-1.17602483,  0.6596948 , -1.1653172 , ..., -0.99833135,
        -1.02222705,  1.33645936],
       [ 1.18684903, -1.34218285,  0.18664186, ..., -0.43363936,
        -0.0933178 , -0.5320456 ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.60790363,
         0.71315642, -0.3167053 ],
       [ 0.78221312, -0.85106801,  0.18664186, ..., -0.05717804,
        -0.37545069,  0.09812139],
       [-1.43579109,  0.99645926,  1.85670895, ..., -0.13515931,
         0.3777909 , -0.15779865]])

## Ordinal Encoding

In [53]:
X_train_cat

17606     <1H OCEAN
18632     <1H OCEAN
14650    NEAR OCEAN
3230         INLAND
3555      <1H OCEAN
            ...    
6563         INLAND
12053        INLAND
13908        INLAND
11159     <1H OCEAN
15775      NEAR BAY
Name: ocean_proximity, Length: 16512, dtype: object

In [54]:
type(X_train_cat)

pandas.core.series.Series

In [55]:
from sklearn.preprocessing import OrdinalEncoder

In [56]:
ord_encoder = OrdinalEncoder()

In [57]:
x_train_cat_encoded = ord_encoder.fit_transform(X_train_cat.values.reshape(-1,1))

In [58]:
x_train_cat_encoded

array([[0.],
       [0.],
       [4.],
       ...,
       [1.],
       [0.],
       [3.]])

In [59]:
ord_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [60]:
from sklearn.preprocessing import OneHotEncoder

In [61]:
hot_encoder = OneHotEncoder()  #Also can be written as OneHotEncoder(sparse=False)

In [62]:
x_train_hot_encoded = hot_encoder.fit_transform(X_train_cat.values.reshape(-1,1))

In [63]:
x_train_hot_encoded[:5]   #Scipy Sparse matrix

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [64]:
x_train_hot_encoded[:5].toarray()

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

# Custom Transformer

In [65]:
from sklearn.base import BaseEstimator, TransformerMixin

In [66]:
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attrs=[]):
        self.attrs = attrs
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attrs]

In [67]:
df_selector = DataFrameSelector(['longitude', 'ocean_proximity'])

In [68]:
housing_lon_ocean = df_selector.fit_transform(housing)

In [69]:
housing_lon_ocean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   longitude        20640 non-null  float64
 1   ocean_proximity  20640 non-null  object 
dtypes: float64(1), object(1)
memory usage: 322.6+ KB


## Base Estimator provides two inherited methods get_params(), and set_paramms()

In [70]:
df_selector.get_params()

{'attrs': ['longitude', 'ocean_proximity']}

In [71]:
# another way to write 
df_selector.get_params('attrs')

{'attrs': ['longitude', 'ocean_proximity']}

In [72]:
from sklearn.pipeline import Pipeline, FeatureUnion

In [73]:
num_pipe = Pipeline([
    ('selector', DataFrameSelector(attrs=X_train.columns[:-1])),
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
cat_pipe = Pipeline([
    ('selector', DataFrameSelector(attrs=['ocean_proximity'])),
    ('hot_encoder', OneHotEncoder(sparse=False))
])
pipe = FeatureUnion([
    ('num_pipe', num_pipe),
    ('cat_pipe', cat_pipe)
])

In [74]:
x_train_final = pipe.fit_transform(X_train)

In [75]:
x_test_final = pipe.fit_transform(X_test)

In [76]:
from sklearn.linear_model import LinearRegression

In [77]:
lin_reg = LinearRegression()

In [78]:
lin_reg.fit(x_train_final, y_train)

LinearRegression()

In [79]:
y_train_hat = lin_reg.predict(x_train_final)

In [80]:
y_train_hat[:5]

array([212480., 321984., 210816.,  61184., 192640.])

In [81]:
y_test[:5]

5241     500001.0
10970    240300.0
20351    218200.0
6568     182100.0
13285    121300.0
Name: median_house_value, dtype: float64

In [82]:
y_test_hat = lin_reg.predict(x_test_final)

In [83]:
y_test_hat[:5]

array([421504., 266368., 227712., 205824., 167616.])

In [84]:
from sklearn.metrics import mean_squared_error

In [85]:
mean_squared_error(y_train, y_train_hat)

4768585336.759024

In [86]:
np.sqrt(mean_squared_error(y_train, y_train_hat))

69054.94433245908

In [87]:
mean_squared_error(y_test, y_test_hat)

4538454549.148255

In [88]:
np.sqrt(mean_squared_error(y_test, y_test_hat))

67368.05288226946

In [89]:
from sklearn.metrics import r2_score

In [90]:
r2_score(y_train, y_train_hat)

0.6437732646066405

In [91]:
r2_score(y_test, y_test_hat)

0.6517357973952633